so ~/.vim/plugins.vim

map ; :Files<CR>

"Highlight search 
set hlsearch

"Vi Theme
colors evening

"indent 4spaces
filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab

"display line numbers
set number
"---------------------------------------------------------------------------
"Highlight when line > 80 columns


function! Show_80col_trailingWhiteSpace()
    highlight ExtraWhitespace ctermbg=Yellow guibg=Yellow
    if &colorcolumn
        :set colorcolumn=
        match ExtraWhitespace //
        echo 'Hiding 80 column + Trailing White Spaces'
    else
        :set colorcolumn=80
        match ExtraWhitespace /\s\+$\|\t/
        echo 'Showing 80 columns + Trailing White Spaces'
    endif
endfunction

function RunWith (command)
  execute "w"
  execute "!clear;time " . a:command . " " . expand("%")
endfunction


function! Save_and_launch()
    execute "w"
    execute "!./%"
endfunction


"Key mapping
  "map <F2> key to display the 80char margin
    map <F2>          :call Show_80col_trailingWhiteSpace()<CR>
    nnoremap <F3> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar><CR>
  "map <F4> key to display file Tree
    "map <F4>          :TlistToggle<CR>
    map <F4>          ::NERDTreeToggle<CR>
    map <F5>          ::TagbarToggle<CR>
  "map <F9> key to execute the current python script
    nnoremap <buffer> <F9> :call Save_and_launch()<CR>

  "save in sudo using :W
    cmap W! execute 'silent w !sudo tee > /dev/null %' \| edit!


augroup myTodo
  autocmd!
  autocmd Syntax * syntax match myTodo /\v\_.<(TODO|FIXME|ToDo).*/hs=s+1 containedin=.*Comment
augroup END

highlight link myTodo Todo


